export default [
    {kanji: "青い", furigana: "あおい", romaji: "aoi", meaning: "blue"},
    {kanji: "赤い", furigana: "あかい", romaji: "akai", meaning: "red"},
    {kanji: "明るい", furigana: "あかるい", romaji: "akarui", meaning: "light, bright"},
    {kanji: "温かい", furigana: "あたたかい", romaji: "atatakai", meaning: "warm"},
    {kanji: "新しい", furigana: "あたらしい", romaji: "atarashii", meaning: "new"},
    {kanji: "暑い", furigana: "あつい", romaji: "atsui", meaning: "hot (air)"},
    {kanji: "厚い", furigana: "あつい", romaji: "atsui", meaning: "thick"},
    {kanji: "危ない", furigana: "あぶない", romaji: "abunai", meaning: "dangerous"},
    {kanji: "甘い", furigana: "あまい", romaji: "amai", meaning: "sweet"},
    {kanji: "良い", furigana: "よい/いい", romaji: "yoi / ii", meaning: "good"},
    {kanji: "忙しい", furigana: "いそがしい", romaji: "isogashii", meaning: "to be busy"},
    {kanji: "痛い", furigana: "いたい", romaji: "itai", meaning: "to be painful"},
    {kanji: "薄い", furigana: "うすい", romaji: "usui", meaning: "thin"},
    {kanji: "美味しい", furigana: "おいしい", romaji: "oishii", meaning: "tasty, delicious"},
    {kanji: "大きい", furigana: "おおきい", romaji: "ookii", meaning: "big"},
    {kanji: "遅い", furigana: "おそい", romaji: "osoi", meaning: "late, slow"},
    {kanji: "重い", furigana: "おもい", romaji: "omoi", meaning: "heavy"},
    {kanji: "面白い", furigana: "おもしろい", romaji: "omoshiroi", meaning: "intersting, funny"},
    {kanji: "辛い", furigana: "からい", romaji: "karai", meaning: "hot, spicy"},
    {kanji: "軽い", furigana: "かるい", romaji: "karui", meaning: "light (not heavy)"},
    {kanji: "可愛い", furigana: "かわいい", romaji: "kawaii", meaning: "cute, pretty"},
    {kanji: "黄色い", furigana: "きいろい", romaji: "kiiroi", meaning: "yellow"},
    {kanji: "汚い", furigana: "きたない", romaji: "kitanai", meaning: "dirty"},
    {kanji: "暗い", furigana: "くらい", romaji: "kurai", meaning: "dark"},
    {kanji: "黒い", furigana: "くろい", romaji: "kuroi", meaning: "black"},
    {kanji: "寒い", furigana: "さむい", romaji: "samui", meaning: "cold"},
    {kanji: "白い", furigana: "しろい", romaji: "shiroi", meaning: "white"},
    {kanji: "涼しい", furigana: "すずしい", romaji: "suzushii", meaning: "cool"},
    {kanji: "狭い", furigana: "せまい", romaji: "semai", meaning: "narrow"},
    {kanji: "高い", furigana: "たかい", romaji: "takai", meaning: "high, expensive"},
    {kanji: "楽しい", furigana: "たのしい", romaji: "tanoshii", meaning: "pleasant, enjoyable"},
    {kanji: "小さい", furigana: "ちいさい", romaji: "chiisai", meaning: "small"},
    {kanji: "近い", furigana: "ちかい", romaji: "chikai", meaning: "near, close"},
    {kanji: "詰らない", furigana: "つまらない", romaji: "tsumaranai", meaning: "uninteresting"},
    {kanji: "冷たい", furigana: "つめたい", romaji: "tsumetai", meaning: "cold"},
    {kanji: "強い", furigana: "つよい", romaji: "tsuyoi", meaning: "strong"},
    {kanji: "遠い", furigana: "とおい", romaji: "tooi", meaning: "far"},
    {kanji: "長い", furigana: "ながい", romaji: "nagai", meaning: "long"},
    {kanji: "早い", furigana: "はやい", romaji: "hayai", meaning: "early"},
    {kanji: "速い", furigana: "はやい", romaji: "hayai", meaning: "fast, quick"},
    {kanji: "低い", furigana: "ひくい", romaji: "hikui", meaning: "low"},
    {kanji: "広い", furigana: "ひろい", romaji: "hiroi", meaning: "wide, spacious"},
    {kanji: "太い", furigana: "ふとい", romaji: "futoi", meaning: "thick, fat"},
    {kanji: "古い", furigana: "ふるい", romaji: "furui", meaning: "old"},
    {kanji: "欲しい", furigana: "ほしい", romaji: "hoshii", meaning: "to want something"},
    {kanji: "細い", furigana: "ほそい", romaji: "hosoi", meaning: "thin, fine"},
    {kanji: "不味い", furigana: "まずい", romaji: "mazui", meaning: "bad tasting"},
    {kanji: "丸い", furigana: "まるい", romaji: "marui", meaning: "round"},
    {kanji: "短い", furigana: "みじかい", romaji: "mijikai", meaning: "short"},
    {kanji: "難しい", furigana: "むずかしい", romaji: "muzukashii", meaning: "difficult"},
    {kanji: "優しい", furigana: "やさしい", romaji: "yasashii", meaning: "gentle"},
    {kanji: "安い", furigana: "やすい", romaji: "yasui", meaning: "cheap"},
    {kanji: "若い", furigana: "わかい", romaji: "wakai", meaning: "young"},
    {kanji: "好き", furigana: "すき", romaji: "suki", meaning: "like, love"},
    {kanji: "結構", furigana: "けっこう", romaji: "kekkou", meaning: "wonderful, enviable"},
    {kanji: "有名", furigana: "ゆうめい", romaji: "yuumei", meaning: "Famous"},
    {kanji: "きれい", furigana: "きれい", romaji: "kirei", meaning: "pretty, beautiful"},
    {kanji: "丁寧", furigana: "ていねい", romaji: "teinei", meaning: "polite"},
    {kanji: "嫌い", furigana: "きらい", romaji: "kirai", meaning: "to not like"},
    {kanji: "静か", furigana: "しずか", romaji: "shizuka", meaning: "quiet"},
    {kanji: "暇", furigana: "ひま", romaji: "hima", meaning: "free (time)"},
    {kanji: "賑やか", furigana: "にぎやか", romaji: "nigiyaka", meaning: "lively"},
    {kanji: "便利", furigana: "べんり", romaji: "benri", meaning: "useful, convenient"},
    {kanji: "元気", furigana: "げんき", romaji: "genki", meaning: "healthy"},
    {kanji: "色々", furigana: "いろいろ", romaji: "iroiro", meaning: "various"},
    {kanji: "大丈夫", furigana: "だいじょうぶ", romaji: "daijoubu", meaning: "ok, fine"},
    {kanji: "丈夫", furigana: "じょうぶ", romaji: "joubu", meaning: "healthy, robust"},
    {kanji: "大変", furigana: "たいへん", romaji: "taihen", meaning: "terrible"},
    {kanji: "楽", furigana: "らく", romaji: "raku", meaning: "comfortable, easy"},
    {kanji: "-", furigana: "いや", romaji: "iya", meaning: "unpleasant"},
    {kanji: "大切", furigana: "たいせつ", romaji: "taisetsu", meaning: "important, precious"},
    {kanji: "上手", furigana: "じょうず", romaji: "jyouzu", meaning: "good, skilled"},
    {kanji: "下手", furigana: "へた", romaji: "heta", meaning: "bad at, unskilled"},
    {kanji: "一生懸命", furigana: "いっしょうけんめい", romaji: "isshoukenmei", meaning: "to one’s fullest possibility"},
    {kanji: "危険", furigana: "きけん", romaji: "kiken", meaning: "dangerous"},
    {kanji: "残念", furigana: "ざんねん", romaji: "zannen", meaning: "regrettable, dissapointing"},
    {kanji: "心配", furigana: "しんぱい", romaji: "shinpai", meaning: "care, worry"},
    {kanji: "自由", furigana: "じゆう", romaji: "jiyuu", meaning: "free, unrestrained"},
    {kanji: "十分", furigana: "じゅうぶん", romaji: "jyuubun", meaning: "sufficient"},
    {kanji: "大好き", furigana: "だいすき", romaji: "daisuki", meaning: "passionate"},
    {kanji: "適当", furigana: "てきとう", romaji: "tekitou", meaning: "proper, suitable"},
    {kanji: "特別", furigana: "とくべつ", romaji: "tokubetsu", meaning: "special"},
    {kanji: "熱心", furigana: "ねっしん", romaji: "nesshin", meaning: "eager, enthusiastic"},
    {kanji: "必要", furigana: "ひつよう", romaji: "hitsuyou", meaning: "necessary"},
    {kanji: "-", furigana: "まじめ", romaji: "majime", meaning: "serious, earnest"},
    {kanji: "真直ぐ", furigana: "まっすぐ", romaji: "massugu", meaning: "straight"},
    {kanji: "無理", furigana: "むり", romaji: "muri", meaning: "unreasonable"},
    {kanji: "立派", furigana: "りっぱ", romaji: "rippa", meaning: "excellent, splendid, fine"},
];



