export default [
    {kanji: "会う", furigana: "あう", romaji: "au", meaning: "to meet"},
    {kanji: "開く", furigana: "あく", romaji: "aku", meaning: "to open"},
    {kanji: "開ける", furigana: "あける", romaji: "akeru", meaning: "to open"},
    {kanji: "-", furigana: "あげる", romaji: "ageru", meaning: "to give"},
    {kanji: "遊ぶ", furigana: "あそぶ", romaji: "asobu", meaning: "to play"},
    {kanji: "浴びる", furigana: "あびる", romaji: "abiru", meaning: "to take a shower"},
    {kanji: "洗う", furigana: "あらう", romaji: "arau", meaning: "to wash"},
    {kanji: "有る", furigana: "ある", romaji: "aru", meaning: "to be, to exist"},
    {kanji: "ある", furigana: "ある", romaji: "aru", meaning: "to possess"},
    {kanji: "歩く", furigana: "あるく", romaji: "aruku", meaning: "to walk"},
    {kanji: "言う", furigana: "いう", romaji: "iu", meaning: "to say, to tell"},
    {kanji: "行く", furigana: "いく", romaji: "iku", meaning: "to go"},
    {kanji: "-", furigana: "いる", romaji: "iru", meaning: "need, must have, be required"},
    {kanji: "-", furigana: "いる", romaji: "iru", meaning: "to exist"},
    {kanji: "入れる", furigana: "いれる", romaji: "ireru", meaning: "to insert, to put in"},
    {kanji: "歌う", furigana: "うたう", romaji: "utau", meaning: "to sing"},
    {kanji: "生まれる", furigana: "うまれる", romaji: "umareru", meaning: "to be born"},
    {kanji: "売る", furigana: "うる", romaji: "uru", meaning: "to sell"},
    {kanji: "起きる", furigana: "おきる", romaji: "okiru", meaning: "to get up, to stand up"},
    {kanji: "-", furigana: "おく", romaji: "oku", meaning: "to put"},
    {kanji: "送る", furigana: "おくる", romaji: "okuru", meaning: "to send"},
    {kanji: "押す", furigana: "おす", romaji: "osu", meaning: "to push"},
    {kanji: "覚える", furigana: "おぼえる", romaji: "oboeru", meaning: "to memorize, to remember"},
    {kanji: "泳ぐ", furigana: "およぐ", romaji: "oyogu", meaning: "to swim"},
    {kanji: "降りる", furigana: "おりる", romaji: "oriru", meaning: "to get off"},
    {kanji: "終わる", furigana: "おわる", romaji: "owaru", meaning: "to end"},
    {kanji: "買う", furigana: "かう", romaji: "kau", meaning: "to buy"},
    {kanji: "返す", furigana: "かえす", romaji: "kaesu", meaning: "to return an object"},
    {kanji: "帰る", furigana: "かえる", romaji: "kaeru", meaning: "to return home"},
    {kanji: "-", furigana: "かかる", romaji: "kakaru", meaning: "to take time or money"},
    {kanji: "書く", furigana: "かく", romaji: "kaku", meaning: "to write"},
    {kanji: "-", furigana: "かける", romaji: "kakeru", meaning: "to wear"},
    {kanji: "-", furigana: "かける", romaji: "kakeru", meaning: "to make a phone call"},
    {kanji: "貸す", furigana: "かす", romaji: "kasu", meaning: "to lend"},
    {kanji: "冠る", furigana: "かぶる", romaji: "kaburu", meaning: "to put on a hat"},
    {kanji: "借りる", furigana: "かりる", romaji: "kariru", meaning: "to borrow"},
    {kanji: "消える", furigana: "きえる", romaji: "kieru", meaning: "to go out, to vanish"},
    {kanji: "聞く", furigana: "きく", romaji: "kiku", meaning: "to listen"},
    {kanji: "切る", furigana: "きる", romaji: "kiru", meaning: "to cut"},
    {kanji: "着る", furigana: "きる", romaji: "kiru", meaning: "to wear, to put on"},
    {kanji: "来る", furigana: "くる", romaji: "kuru", meaning: "to come"},
    {kanji: "消す", furigana: "けす", romaji: "kesu", meaning: "to turn off, to switch off"},
    {kanji: "答える", furigana: "こたえる", romaji: "kotaeru", meaning: "to answer"},
    {kanji: "困る", furigana: "こまる", romaji: "komaru", meaning: "to be in trouble"},
    {kanji: "咲く", furigana: "さく", romaji: "saku", meaning: "to blossom"},
    {kanji: "-", furigana: "さす", romaji: "sasu", meaning: "to open an umbrella"},
    {kanji: "死ぬ", furigana: "しぬ", romaji: "shinu", meaning: "to die, to pass away"},
    {kanji: "閉まる", furigana: "しまる", romaji: "shimaru", meaning: "to close"},
    {kanji: "閉める", furigana: "しめる", romaji: "shimeru", meaning: "to close"},
    {kanji: "締める", furigana: "しめる", romaji: "shimeru", meaning: "to fasten a belt"},
    {kanji: "知る", furigana: "しる", romaji: "shiru", meaning: "to know"},
    {kanji: "吸う", furigana: "すう", romaji: "suu", meaning: "to breath, to smoke"},
    {kanji: "住む", furigana: "すむ", romaji: "sumu", meaning: "to live, to reside somewhere"},
    {kanji: "する", furigana: "する", romaji: "suru", meaning: "to do"},
    {kanji: "座る", furigana: "すわる", romaji: "suwaru", meaning: "to sit"},
    {kanji: "出す", furigana: "だす", romaji: "dasu", meaning: "to take out, hand in"},
    {kanji: "立つ", furigana: "たつ", romaji: "tatsu", meaning: "to stand"},
    {kanji: "頼む", furigana: "たのむ", romaji: "tanomu", meaning: "to ask, to request"},
    {kanji: "食べる", furigana: "たべる", romaji: "taberu", meaning: "to eat"},
    {kanji: "違う", furigana: "ちがう", romaji: "chigau", meaning: "to be different"},
    {kanji: "使う", furigana: "つかう", romaji: "tsukau", meaning: "to use"},
    {kanji: "疲れる", furigana: "つかれる", romaji: "tsukareru", meaning: "to get tired"},
    {kanji: "着く", furigana: "つく", romaji: "tsuku", meaning: "to arrive"},
    {kanji: "作る", furigana: "つくる", romaji: "tsukuru", meaning: "to make, to produce"},
    {kanji: "点ける", furigana: "つける", romaji: "tsukeru", meaning: "to turn on"},
    {kanji: "勤める", furigana: "つとめる", romaji: "tsutomeru", meaning: "to work for someone"},
    {kanji: "出かける", furigana: "でかける", romaji: "dekakeru", meaning: "to go out"},
    {kanji: "出来る", furigana: "できる", romaji: "dekiru", meaning: "can do"},
    {kanji: "出る", furigana: "でる", romaji: "deru", meaning: "to leave"},
    {kanji: "飛ぶ", furigana: "とぶ", romaji: "tobu", meaning: "to fly"},
    {kanji: "止まる", furigana: "とまる", romaji: "tomaru", meaning: "to stop"},
    {kanji: "取る", furigana: "とる", romaji: "toru", meaning: "to take"},
    {kanji: "撮る", furigana: "とる", romaji: "toru", meaning: "to take a photo"},
    {kanji: "鳴く", furigana: "なく", romaji: "naku", meaning: "to sing, mew, moo"},
    {kanji: "並ぶ", furigana: "ならぶ", romaji: "narabu", meaning: "to form a line"},
    {kanji: "並べる", furigana: "ならべる", romaji: "naraberu", meaning: "to line up"},
    {kanji: "なる", furigana: "naru", romaji: "to", meaning: "become"},
    {kanji: "脱ぐ", furigana: "ぬぐ", romaji: "nugu", meaning: "to take off clothes"},
    {kanji: "寝る", furigana: "ねる", romaji: "neru", meaning: "to sleep"},
    {kanji: "登る", furigana: "のぼる", romaji: "noboru", meaning: "to climb up"},
    {kanji: "飲む", furigana: "のむ", romaji: "nomu", meaning: "to drink"},
    {kanji: "乗る", furigana: "のる", romaji: "noru", meaning: "to take, to ride"},
    {kanji: "入る", furigana: "はいる", romaji: "hairu", meaning: "to enter"},
    {kanji: "履く", furigana: "はく", romaji: "haku", meaning: "to put on shoes"},
    {kanji: "始まる", furigana: "はじまる", romaji: "hajimaru", meaning: "to begin, to start"},
    {kanji: "走る", furigana: "はしる", romaji: "hashiru", meaning: "to run"},
    {kanji: "働く", furigana: "はたらく", romaji: "hataraku", meaning: "to work"},
    {kanji: "話す", furigana: "はなす", romaji: "hanasu", meaning: "to talk, to speak, to tell"},
    {kanji: "張る", furigana: "はる", romaji: "haru", meaning: "to put something on, to stick"},
    {kanji: "晴れる", furigana: "はれる", romaji: "hareru", meaning: "to clear up"},
    {kanji: "引く", furigana: "ひく", romaji: "hiku", meaning: "to pull"},
    {kanji: "弾く", furigana: "ひく", romaji: "hiku", meaning: "to play an instrument"},
    {kanji: "吹く", furigana: "ふく", romaji: "fuku", meaning: "to blow (wind)"},
    {kanji: "降る", furigana: "ふる", romaji: "furu", meaning: "to fall (rain, snow)"},
    {kanji: "曲がる", furigana: "まがる", romaji: "magaru", meaning: "to turn"},
    {kanji: "待つ", furigana: "まつ", romaji: "matsu", meaning: "to wait"},
    {kanji: "磨く", furigana: "みがく", romaji: "migaku", meaning: "to polish, to brush"},
    {kanji: "見せる", furigana: "みせる", romaji: "miseru", meaning: "to show"},
    {kanji: "見る", furigana: "みる", romaji: "miru", meaning: "to see, to watch"},
    {kanji: "持つ", furigana: "もつ", romaji: "motsu", meaning: "to have, to own"},
    {kanji: "休む", furigana: "やすむ", romaji: "yasumu", meaning: "to rest"},
    {kanji: "-", furigana: "やる", romaji: "yaru", meaning: "to do"},
    {kanji: "呼ぶ", furigana: "よぶ", romaji: "yobu", meaning: "to call"},
    {kanji: "読む", furigana: "よむ", romaji: "yomu", meaning: "to read"},
    {kanji: "分かる", furigana: "わかる", romaji: "wakaru", meaning: "to know, to understand"},
    {kanji: "忘れる", furigana: "わすれる", romaji: "wasureru", meaning: "to forget"},
    {kanji: "渡す", furigana: "わたす", romaji: "watasu", meaning: "to hand over"},
    {kanji: "渡る", furigana: "わたる", romaji: "wataru", meaning: "to cross"},
];